version: "3.7"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client

  server:
    build: ./server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PoGoTrades
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    depends_on:
      - database
    command: ["./wait-for-it.sh", "database:5432", "--", "nodemon"]

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PoGoTrades
    volumes:
      - ~/databases/PoGoTrades:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
